USE db_numismaster;

INSERT INTO TB_Country (name, code) VALUES
('Afeganistão', 'AF'),
('Ilhas Aland', 'AX'),
('Albânia', 'AL'),
('Argélia', 'DZ'),
('Samoa Americana', 'AS'),
('Andorra', 'AD'),
('Angola', 'AO'),
('Anguilla', 'AI'),
('Antártica', 'AQ'),
('Antigua e Barbuda', 'AG'),
('Argentina', 'AR'),
('Armênia', 'AM'),
('Aruba', 'AW'),
('Austrália', 'AU'),
('Áustria', 'AT'),
('Azerbaijão', 'AZ'),
('Bahamas', 'BS'),
('Bahrain', 'BH'),
('Bangladesh', 'BD'),
('Barbados', 'BB'),
('Bielo-Rússia', 'BY'),
('Bélgica', 'BE'),
('Belize', 'BZ'),
('Benin', 'BJ'),
('Bermudas', 'BM'),
('Butão', 'BT'),
('Bolívia', 'BO'),
('Bonaire, Sint Eustatius e Saba', 'BQ'),
('Bósnia e Herzegovina', 'BA'),
('Botswana', 'BW'),
('Ilha Bouvet', 'BV'),
('Brasil', 'BR'),
('Território Britânico do Oceano Índico', 'IO'),
('Brunei Darussalam', 'BN'),
('Bulgária', 'BG'),
('Burkina Faso', 'BF'),
('Burundi', 'BI'),
('Camboja', 'KH'),
('Camarões', 'CM'),
('Canadá', 'CA'),
('Cabo Verde', 'CV'),
('Ilhas Cayman', 'KY'),
('República Centro-Africana', 'CF'),
('Chade', 'TD'),
('Chile', 'CL'),
('China', 'CN'),
('Ilha do Natal', 'CX'),
('Ilhas Cocos (Keeling)', 'CC'),
('Colômbia', 'CO'),
('Comores', 'KM'),
('Congo', 'CG'),
('Congo, República Democrática do Congo', 'CD'),
('Ilhas Cook', 'CK'),
('Costa Rica', 'CR'),
('Cote D\'Ivoire', 'CI'),
('Croácia', 'HR'),
('Cuba', 'CU'),
('Curaçao', 'CW'),
('Chipre', 'CY'),
('República Checa', 'CZ'),
('Dinamarca', 'DK'),
('Djibouti', 'DJ'),
('Dominica', 'DM'),
('República Dominicana', 'DO'),
('Equador', 'EC'),
('Egito', 'EG'),
('El Salvador', 'SV'),
('Guiné Equatorial', 'GQ'),
('Eritreia', 'ER'),
('Estônia', 'EE'),
('Etiópia', 'ET'),
('Ilhas Falkland (Malvinas)', 'FK'),
('ilhas Faroe', 'FO'),
('Fiji', 'FJ'),
('Finlândia', 'FI'),
('França', 'FR'),
('Guiana Francesa', 'GF'),
('Polinésia Francesa', 'PF'),
('Territórios Franceses do Sul', 'TF'),
('Gabão', 'GA'),
('Gâmbia', 'GM'),
('Georgia', 'GE'),
('Alemanha', 'DE'),
('Gana', 'GH'),
('Gibraltar', 'GI'),
('Grécia', 'GR'),
('Groenlândia', 'GL'),
('Grenada', 'GD'),
('Guadalupe', 'GP'),
('Guam', 'GU'),
('Guatemala', 'GT'),
('Guernsey', 'GG'),
('Guiné', 'GN'),
('Guinea-bissau', 'GW'),
('Guiana', 'GY'),
('Haiti', 'HT'),
('Ilha Heard e Ilhas McDonald', 'HM'),
('Santa Sé (Estado da Cidade do Vaticano)', 'VA'),
('Honduras', 'HN'),
('Hong Kong', 'HK'),
('Hungria', 'HU'),
('Islândia', 'IS'),
('Índia', 'IN'),
('Indonésia', 'ID'),
('Irã (Republic Islâmica do Irã', 'IR'),
('Iraque', 'IQ'),
('Irlanda', 'IE'),
('Ilha de Man', 'IM'),
('Israel', 'IL'),
('Itália', 'IT'),
('Jamaica', 'JM'),
('Japão', 'JP'),
('Jersey', 'JE'),
('Jordânia', 'JO'),
('Cazaquistão', 'KZ'),
('Quênia', 'KE'),
('Kiribati', 'KI'),
('Coréia, República Popular Democrática da', 'KP'),
('Republica da Coréia', 'KR'),
('Kosovo', 'XK'),
('Kuwait', 'KW'),
('Quirguistão', 'KG'),
('República Democrática Popular do Laos', 'LA'),
('Letônia', 'LV'),
('Líbano', 'LB'),
('Lesoto', 'LS'),
('Libéria', 'LR'),
('Jamahiriya Árabe da Líbia', 'LY'),
('Liechtenstein', 'LI'),
('Lituânia', 'LT'),
('Luxemburgo', 'LU'),
('Macau', 'MO'),
('Macedônia, Antiga República Iugoslava da', 'MK'),
('Madagáscar', 'MG'),
('Malawi', 'MW'),
('Malásia', 'MY'),
('Maldivas', 'MV'),
('Mali', 'ML'),
('Malta', 'MT'),
('Ilhas Marshall', 'MH'),
('Martinica', 'MQ'),
('Mauritânia', 'MR'),
('Maurício', 'MU'),
('Mayotte', 'YT'),
('México', 'MX'),
('Micronésia, Estados Federados da', 'FM'),
('Moldávia, República da', 'MD'),
('Mônaco', 'MC'),
('Mongólia', 'MN'),
('Montenegro', 'ME'),
('Montserrat', 'MS'),
('Marrocos', 'MA'),
('Moçambique', 'MZ'),
('Myanmar', 'MM'),
('Namibia', 'NA'),
('Nauru', 'NR'),
('Nepal', 'NP'),
('Países Baixos', 'NL'),
('Antilhas Holandesas', 'AN'),
('Nova Caledônia', 'NC'),
('Nova Zelândia', 'NZ'),
('Nicarágua', 'NI'),
('Níger', 'NE'),
('Nigéria', 'NG'),
('Niue', 'NU'),
('Ilha Norfolk', 'NF'),
('Ilhas Marianas do Norte', 'MP'),
('Noruega', 'NO'),
('Omã', 'OM'),
('Paquistão', 'PK'),
('Palau', 'PW'),
('Território Palestino, Ocupado', 'PS'),
('Panamá', 'PA'),
('Papua Nova Guiné', 'PG'),
('Paraguai', 'PY'),
('Peru', 'PE'),
('Filipinas', 'PH'),
('Pitcairn', 'PN'),
('Polônia', 'PL'),
('Portugal', 'PT'),
('Porto Rico', 'PR'),
('Catar', 'QA'),
('Reunião', 'RE'),
('Romênia', 'RO'),
('Federação Russa', 'RU'),
('Ruanda', 'RW'),
('São Bartolomeu', 'BL'),
('Santa Helena', 'SH'),
('São Cristóvão e Neves', 'KN'),
('Santa Lúcia', 'LC'),
('são Martinho', 'MF'),
('São Pedro e Miquelão', 'PM'),
('São Vicente e Granadinas', 'VC'),
('Samoa', 'WS'),
('San Marino', 'SM'),
('São Tomé e Príncipe', 'ST'),
('Arábia Saudita', 'SA'),
('Senegal', 'SN'),
('Sérvia', 'RS'),
('Sérvia e Montenegro', 'CS'),
('Seychelles', 'SC'),
('Serra Leoa', 'SL'),
('Cingapura', 'SG'),
('St Martin', 'SX'),
('Eslováquia', 'SK'),
('Eslovênia', 'SI'),
('Ilhas Salomão', 'SB'),
('Somália', 'SO'),
('África do Sul', 'ZA'),
('Geórgia do Sul e Ilhas Sandwich do Sul', 'GS'),
('Sudão do Sul', 'SS'),
('Espanha', 'ES'),
('Sri Lanka', 'LK'),
('Sudão', 'SD'),
('Suriname', 'SR'),
('Svalbard e Jan Mayen', 'SJ'),
('Suazilândia', 'SZ'),
('Suécia', 'SE'),
('Suíça', 'CH'),
('República Árabe da Síria', 'SY'),
('Taiwan, província da China', 'TW'),
('Tajiquistão', 'TJ'),
('Tanzânia, República Unida da', 'TZ'),
('Tailândia', 'TH'),
('Timor-Leste', 'TL'),
('Ir', 'TG'),
('Tokelau', 'TK'),
('Tonga', 'TO'),
('Trinidad e Tobago', 'TT'),
('Tunísia', 'TN'),
('Turquia', 'TR'),
('Turcomenistão', 'TM'),
('Ilhas Turcas e Caicos', 'TC'),
('Tuvalu', 'TV'),
('Uganda', 'UG'),
('Ucrânia', 'UA'),
('Emirados Árabes Unidos', 'AE'),
('Reino Unido', 'GB'),
('Estados Unidos', 'US'),
('Ilhas Menores Distantes dos Estados Unidos', 'UM'),
('Uruguai', 'UY'),
('Uzbequistão', 'UZ'),
('Vanuatu', 'VU'),
('Venezuela', 'VE'),
('Vietnam', 'VN'),
('Ilhas Virgens Britânicas', 'VG'),
('Ilhas Virgens, EUA', 'VI'),
('Wallis e Futuna', 'WF'),
('Saara Ocidental', 'EH'),
('Iémen', 'YE'),
('Zâmbia', 'ZM'),
('Zimbábue', 'ZW');

INSERT INTO TB_User (username, first_name, last_name, gender, password, birth_date, email, cpf)
VALUES
('johndoe', 'John', 'Doe', 0,'pa$$w0rd1',  '1985-01-01', 'johndoe@email.com', '12345678901'),
('janedoe', 'Jane', 'Doe', 1,'pa$$w0rd2',  '1987-02-02', 'janedoe@email.com', '12345678902'),
('jimsmith', 'Jim', 'Smith', 0,'pa$$w0rd3',  '1989-03-03', 'jimsmith@email.com', '12345678903'),
('sarahjones', 'Sarah', 'Jones', 1, 'pa$$w0rd4',  '1991-04-04', 'sarahjones@email.com', '12345678904'),
('mikebrown', 'Mike', 'Brown', 0,'pa$$w0rd5', '1993-05-05', 'mikebrown@email.com', '12345678905'),
('jenniferwhite', 'Jennifer', 'White', 1, 'pa$$w0rd6', '1995-06-06', 'jenniferwhite@email.com', '12345678906'),
('davidsmith', 'David', 'Smith', 0, 'pa$$w0rd7', '1997-07-07', 'davidsmith@email.com', '12345678907'),
('emmamiller', 'Emma', 'Miller', 1, 'pa$$w0rd8', '1999-08-08', 'emmamiller@email.com', '12345678908'),
('williamjones', 'William', 'Jones', 0, 'pa$$w0rd9', '2001-09-09', 'williamjones@email.com', '12345678909'),
('oliviagreen', 'Olivia', 'Green', 1, 'pa$$w0rd10', '2003-10-10', 'oliviagreen@email.com', '12345678910');

INSERT INTO TB_Shape (name) 
VALUES 
("Circular"), 
("Quadrado"), 
("Esfera"), 
("Triangular");

INSERT INTO TB_Material (name)
VALUES
("Ferro"),
("Chumbo"),
("Estanho"),
("Cobre"),
("Ouro"),
("Prata"),
("Madeira"),
("Platina"),
("Bronze"),
("Aço");

INSERT INTO TB_Edge (name)
VALUES
("Lisa"),
("Serrilhada"),
("Plana"),
("Inscrita"),
("Dentada");

INSERT INTO TB_Coin (name, country_id, denomination, weight, diameter, thickness, rarity)
VALUES
('1 Real (XXXI Olimpíadas de Verão de 2016 no Rio - Rugby)', 32, 1.00, 7, 27, 1.95, 1),
('1 Real (XXXI Olimpíadas de Verão de 2016 no Rio - Futebol)', 32, 1.00, 7, 27, 1.95, 1),
('1 Real (XXXI Olimpíadas de Verão de 2016 no Rio - Basquete)', 32, 1.00, 7, 27, 1.95, 1),
('1 Real (XXXI Olimpíadas de Verão de 2016 no Rio - Paracanoagem)', 32, 1.00, 7, 27, 1.95, 1);

INSERT INTO TB_Coin_Material (coin_id, material_id)
VALUES
(1, 1),
(1, 4),
(2, 1),
(2, 4),
(3, 1),
(3, 4),
(4, 1),
(4, 4);

INSERT INTO TB_Coin_Shape (coin_id, shape_id)
VALUES
(1, 1),
(2, 1),
(3, 1),
(4, 1);

INSERT INTO TB_Coin_Edge (coin_id, edge_id)
VALUES
(1, 1),
(1, 2),
(2, 1),
(2, 2),
(3, 1),
(3, 2),
(4, 1),
(4, 2);

INSERT INTO TB_Coin_User (user_id, coin_id, year, coin_condition, is_for_sale, price)
VALUES
(1, 1, 2016, 0, 1, 49.90),
(1, 2, 2016, 1, 0, 0),
(1, 3, 2016, 0, 1, 54.90),
(1, 4, 2016, 1, 0, 0);